### ISSUE TITLE
Researching Github repositories and reporting them on Wiki

### ISSUE THREAD

**Issue by aemresafak** [bounswe/bounswe2023group4#11]
At the last week's lecture of CMPE352, our instructor Suzan Uskudarli gave our team a task. The task consists of finding a repository that we like the most, summarize it, point out what we dislike and like about it. Our team member @AliNasra has already created his [research page](https://github.com/bounswe/bounswe2023group4/wiki/Favorite-Repository-(Ali-Nasra)). Each team member should conform to the template decided by the team and report their favorite repository. The template is the one that is used by @AliNasra. Please refer to his [page](https://github.com/bounswe/bounswe2023group4/wiki/Favorite-Repository-(Ali-Nasra)) for more details.

### Tasks
- [x] Research page of Ali Nasra
- [x] Research page of Yiğit Şekerci
- [x] Research page of Selin Işık
- [x] Research page of Ahmet Emre Şafak
- [x] Research page of Ali Alperen Sönmez
- [x] Research page of Emre Batuhan Göç
- [x] Research page of Halil Özkan
- [x] Research page of Yusuf Suat Polat
- [x] Research page of Enes Furkan Arslan

**Comment by aemresafak** [comment]
I have created my [research page](https://github.com/bounswe/bounswe2023group4/wiki/Favorite-Repository-(Ahmet-Emre-%C5%9Eafak)). Can someone check and mark my task as done?

**Comment by EmreBatuhan** [comment]
I have also created my [research page](https://github.com/bounswe/bounswe2023group4/wiki/Favorite-Repository-(Emre-Batuhan-G%C3%B6%C3%A7)) Can someone check and mark my task as done?

**Comment by YigitSekerci** [comment]
Review my [page](https://github.com/bounswe/bounswe2023group4/wiki/Favorite-Repository-(Yiğit-Şekerci)) please.

**Comment by enfurars** [comment]
I have also completed [my favorite repository page](https://github.com/bounswe/bounswe2023group4/wiki/Favorite-Repository-(Enes%20Furkan%20Arslan)). Can somebody please check on it and close my task?

**Comment by AliAlperenSonmez** [comment]
I have also created my [research page](https://github.com/bounswe/bounswe2023group4/wiki/Favorite-Repository-(Ali-Alperen-S%C3%B6nmez)). Can someone check and mark my task as done?

**Comment by selinisik** [comment]
I have also created my [research page](https://github.com/bounswe/bounswe2023group4/wiki/Favorite-Repository-(Selin-I%C5%9F%C4%B1k)). Can someone check and mark my task as done?

**Comment by carmendetroit** [comment]
I am done with my [research page](https://github.com/bounswe/bounswe2023group4/wiki/Favorite-Repository-(Yusuf-Suat-Polat)).

**Comment by skywllker** [comment]
I have done my research page, can you check my page and add it to research?
